### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by kangqiao-ctrl** [ly0/jlu-drcom-client#5]
我下载的就是这版drcom for jlu ，在openwrt上用，赋予权限之后链接网络，连上了大概半个小时之后突然就断掉了，reboot路由器也没有效果，一晚上再也没成功过，打开网页就提示请登录drcom客户端。是因为我路由器的缓存不够吗？128mb应该没问题的呀…求解答@ly0

另，真的感谢@ly0，吉大这种用定制版drcom的鬼畜学校都想办法弄出了openwrt版，真的强

**Comment by ly0** [comment]
你有试过在PC上运行脚本看看结果么?
赞吉大这鬼畜学校 233333

**Comment by kangqiao-ctrl** [comment]
ok 我现在在理化楼直连区  一会回宿舍去单独运行脚本试试看

**Comment by kangqiao-ctrl** [comment]
已经完全退出登录，输入网址会提示登录drcom的情况下运行脚本

> > > ================================ RESTART ================================
> > > 
> > > config path:d:/etc/drcom.conf
> > > auth svr:10.100.61.3
> > > username:xxxxxxxx #手动逆天改命#
> > > password:********
> > > mac:0xf46d04e3802fL
> > > os:MSDOS 8.0
> > > hostname: localhost
> > > DrCOM Auth Router Ver 1.2
> > > Version feature:
> > > [1] Auto Anti droping connection
> > > [2] Stronger exception handling.
> > > [DEBUG] challenge:
> > > 0202f3a75f975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500ae000000276d0000ffffffffff00000000004472636f0a643d03ccd1318cb9420142b00500030110
> > > [DEBUG] challenge:
> > > 020249a85f975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500af000000276d0000ffffffffff00000000004472636f0a643d03ced1318cb9420144b00500030110
> > > [DEBUG] challenge:
> > > 02026ea85f975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] recvfrom timeout,retrying...
> > > [DEBUG] challenge:
> > > 02021aa85f975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b0000000276d0000ffffffffff00000000004472636f0a643d03d8d1318cb942014eb00500030110
> > > [DEBUG] challenge:
> > > 0202e6a769975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b0000000276d0000ffffffffff00000000004472636f0a643d03dcd1318cb9420152b00500030110
> > > [DEBUG] challenge:
> > > 020276a869975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] recvfrom timeout,retrying...
> > > [DEBUG] challenge:
> > > 02024ea869975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b1000000276d0000ffffffffff00000000004472636f0a643d03e4d1318cb942015ab00500030110
> > > [DEBUG] challenge:
> > > 0202f8a769975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b2000000276d0000ffffffffff00000000004472636f0a643d03e9d1318cb942015fb00500030110
> > > [DEBUG] challenge:
> > > 02027da872975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b2000000276d0000ffffffffff00000000004472636f0a643d03ecd1318cb9420162b00500030110
> > > [DEBUG] challenge:
> > > 02020ea872975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b3000000276d0000ffffffffff00000000004472636f0a643d03edd1318cb9420163b00500030110
> > > [DEBUG] challenge:
> > > 020218a872975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] recvfrom timeout,retrying...
> > > [DEBUG] challenge:
> > > 020271a87c975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b4000000276d0000ffffffffff00000000004472636f0a643d03fad1318cb9420170b00500030110
> > > [DEBUG] challenge:
> > > 020271a87c975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b6000000276d0000ffffffffff00000000004472636f0a643d03fbd1318cb9420171b00500030110
> > > [DEBUG] challenge:
> > > 0202a8a87c975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] recvfrom timeout,retrying...
> > > [DEBUG] challenge:
> > > 02025ca87c975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b7000000276d0000ffffffffff00000000004472636f0a643d0308d2318cb942017eb00500030110
> > > [DEBUG] challenge:
> > > 020263a88a975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500b8000000276d0000ffffffffff00000000004472636f0a643d030cd2318cb9420182b00500030110
> > > [DEBUG] challenge:
> > > 02027aa88a975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] recvfrom timeout,retrying...
> > > [DEBUG] challenge:
> > > 0202bfa88a975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500ba000000276d0000ffffffffff00000000004472636f0a643d0311d2318cb9420187b00500030110
> > > [DEBUG] challenge:
> > > 020250a88a975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500bb000000276d0000ffffffffff00000000004472636f0a643d0315d2318cb942018bb00500030110
> > > [DEBUG] challenge:
> > > 02021ea891975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] recvfrom timeout,retrying...
> > > [DEBUG] challenge:
> > > 0202ffa791975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500bc000000276d0000ffffffffff00000000004472636f0a643d031cd2318cb9420192b00500030110
> > > [DEBUG] challenge:
> > > 0202f3a791975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500bc000000276d0000ffffffffff00000000004472636f0a643d0320d2318cb9420196b00500030110
> > > [DEBUG] challenge:
> > > 0202faa791975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] recvfrom timeout,retrying...
> > > [DEBUG] challenge:
> > > 020221a89a975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500bd000000276d0000ffffffffff00000000004472636f0a643d0327d2318cb942019db00500030110
> > > [DEBUG] challenge:
> > > 0202c2a89a975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500be000000276d0000ffffffffff00000000004472636f0a643d0329d2318cb942019fb00500030110
> > > [DEBUG] challenge:
> > > 020274a89a975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] recvfrom timeout,retrying...
> > > [DEBUG] challenge:
> > > 0202eba79a975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500be000000276d0000ffffffffff00000000004472636f0a643d0332d2318cb94201a7b00500030110
> > > [DEBUG] challenge:
> > > 020279a8a1975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] server return exception.retry
> > > [login] last packet server returned:
> > > 0400000500bf000000276d0000ffffffffff00000000004472636f0a643d0337d2318cb94201acb00500030110
> > > [DEBUG] challenge:
> > > 0202e8a7a1975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] recvfrom timeout,retrying...
> > > [DEBUG] challenge:
> > > 02027ea8a1975d0001000100f203e8f000000000318cb942f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
> > > [challenge] challenge packet sent.
> > > [login] packet sent.
> > > [login] wrong password.
> > > [login] login sent
> > > [keep-alive2] keep-alive2 loop was in daemon.

在一顿retry之后提示wrong password，之后就可以上网了，一副登录成功的样子…打开网页什么的也不会再提示登录drcom
这属于什么现象（

**Comment by kangqiao-ctrl** [comment]
刚才在路由器上再次运行了一次，目前还是成功的。一会我打算挂个机监视一下看看何时会断网…

update 不行 还是30分钟之后自动就断掉 怎么重新弄都不行 我现在打算先在pc上用脚本登陆上 之后fping一下录个日志…

update 16:49
用wired.py登陆后一下午都非常稳定
怎么路由器就不行呢…

**Comment by ly0** [comment]
怀疑是路由器上跑挂了 喵

**Comment by kangqiao-ctrl** [comment]
代码肯定没问题，一定是我路由器的锅
只是不知道是哪部分的锅…

**Comment by ly0** [comment]
换个路由器试试喵

**Comment by kangqiao-ctrl** [comment]
又测试了一晚，情况如下。
1 昨晚路由器上的脚本第一次崩溃之后，尝试在pc端运行脚本，在一顿retry之后登陆成功，网页可以访问，而且WIFI连接的设备也可正常访问互联网。
2 将路由器和pc都关掉，直到开机后打开网页提示需要登录drcom，用putty在路由器端运行脚本，pc端ping 163.com并留日志，从晚上11点测试至早晨7点，日志记录均无异常，结果是在我用winscp登录路由器的时候突然崩溃，登录网页提示需要drcom，这一点我目前还没想通是怎么回事。
3 这次崩溃在putty中可以看出，服务器因为密码错误而在疯狂的退包，脚本retry，retry到一定时候就崩溃了。这让我想起本科的时候有的时候登陆drcom，前两次登录都会提示密码错误而第三次才会登录成功，也是原因不明。

再有，pc上不登录不运行脚本、路由器杀掉进程的情况下，只要上一次脚本没有崩溃，即使计算机和路由器都重启或者断电，网页依然可以访问，所以我想问问有没有一个logout的办法方便测试…谢谢啦，或者说是不是禁用端口61440也可以达到我要的效果？

PS 一块703已经在路上了 换换口味 说不定有奇效呢

**Comment by ly0** [comment]
不知道你路由器啥型号，python蛮吃CPU的，如果路由器不行，开着python外加挂着下载就容易挂

**Comment by kangqiao-ctrl** [comment]
我路由器是buffalo g450h 
https://wikidevi.com/wiki/Buffalo_WZR-HP-G450H 
32M Flash 64M RAM 
之前一直以为是64+128…记错了

中午把那两个jludrcom的lua给删了，之后在hotplug.d里写了个开机启动…一会回去看看有没有崩

2015/10/7
问题已解决，可以关闭了。原因是jludrcom.lua我当时没有配置好，按完按钮之后不能保证wired.py进程一直存在，所以就相当于登陆一次之后就退出了drcom，之后30分钟后被踢。

装好python环境后hotplug完美解决。谢谢@ly0！
